### ISSUE TITLE
Build Failure in gltf_viewer: Resource name must contain only lowercase files

### ISSUE THREAD

**Issue by luc4smoreira** [m4gr3d/Godot-Android-Plugin-Template#1]
**Environment**
IDE: Android Studio Giraffe | 2022.3.1 
Computer: Mac Mini M1

**Description**

I encountered a build failure when trying to run the gltf_viewer app in the Godot-Android-Samples project. The issue seems to be related to a resource naming convention.

**Steps do Reproduce:**

1. Clone the repository
2. Run the command:
`./gradlew :apps:gltf_viewer:installDebug`
3. Observe the build failure:

> Godot-Android-Samples/apps/gltf_viewer/src/main/res/drawable-nodpi/iceCreamCup.png: Resource and asset merger: 'C' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
> 
> FAILURE: Build failed with an exception.

**Comment by luc4smoreira** [comment]
To fix this issue, I have renamed the files to lowercase in the folder:

`Godot-Android-Samples/apps/gltf_viewer/src/main/res/drawable-nodpi`

This aligns with the Android naming conventions that require resource names to be all in lowercase. I have made a commit with these changes in my fork, which can be found here:

 [Renamed images to lowercase for Android resource naming compliance.](https://github.com/luc4smoreira/Godot-Android-Plugin-Template/commit/9de2c29e56f02593989f6613bd06d2fa7b6a783c#diff-2cff4713e03352015f247804da4245d098ddeb325560a3c5bb6e5cfef21e910d)

Unfortunately, I am unable to create a pull request for this change as GitHub is not recognizing the difference in file names due to case sensitivity issues.

Please check if this change resolves the issue. I am available for any further adjustments or discussions if needed.

**Comment by m4gr3d** [comment]
@luc4smoreira This issue was opened in the wrong repo, it should be opened in the [Godot-Android-Samples](https://github.com/m4gr3d/Godot-Android-Samples) repo instead.
