### ISSUE TITLE
App crash with java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by code-with-max** [m4gr3d/Godot-Android-Plugin-Template#2]
Hello.
App died with java.lang.ClassNotFoundException when I used this template.

```
2-13 11:28:55.970  5464  5464 F DEBUG   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.GoogleApiAvailability" on path: DexPathList[[zip file "/data/app/~~5i67fVLY5Ef9yC4AfWCKlw==/org.godotengine.classicsnake-ZMW6o20AcigpqLXz7bibYQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~5i67fVLY5Ef9yC4AfWCKlw==/org.godotengine.classicsnake-ZMW6o20AcigpqLXz7bibYQ==/lib/x86_64, /data/app/~~5i67fVLY5Ef9yC4AfWCKlw==/org.godotengine.classicsnake-ZMW6o20AcigpqLXz7bibYQ==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
```

It`s crashed with any imported classes, not only GoogleApiAvailability, also task.Task and others.

```
import com.google.android.gms.common.GoogleApiAvailability
import com.google.android.gms.tasks.*
```

upd:
https://github.com/godotengine/godot/issues/86152

**Comment by lettdev** [comment]
Same error, it seems that the classes from dependencies are not included in the apk's classes.dex and game always crash with java.lang.ClassNotFoundException. I try a lot of different way but no luck

**Comment by kyadalu1** [comment]
I face similar issue [here](https://github.com/m4gr3d/Godot-Android-Samples/issues/13)

**Comment by code-with-max** [comment]
@lettdev 
@kyadalu1 

Solution
https://github.com/godotengine/godot/issues/86152#issuecomment-1858817419

**Comment by m4gr3d** [comment]
@trash-max @lettdev @kyadalu1  The dependencies you're trying to import are not included in the Godot Android library since they're not part of the Godot project; they're part of Google's set of libraries.

To include them in your project, you need to update [`build.gradle.kts`](https://github.com/m4gr3d/Godot-Android-Plugin-Template/blob/73b394d89241671b7f6c04499886316dc1f3a01a/plugin/build.gradle.kts#L41) and the `_get_android_dependencies` method with the [correct build dependencies](https://developer.android.com/build/dependencies).

**Comment by kyadalu1** [comment]
@m4gr3d  Godot relies on kotlin v1.7.0 so i think coroutines needs to be added as separate dependency.  In many of my native android projects which uses kotlin v1.9.20 and even for some which uses kotlin v1.8.20, i never had to add couroutines as separate dependency. 

Will Godot 4.3 update kotlin version to 1.8 or 1.9?

**Comment by m4gr3d** [comment]
> @m4gr3d Godot relies on kotlin v1.7.0 so i think coroutines needs to be added as separate dependency. In many of my native android projects which uses kotlin v1.9.20 and even for some which uses kotlin v1.8.20, i never had to add couroutines as separate dependency.
> 
> Will Godot 4.3 update kotlin version to 1.8 or 1.9?

Yes, we should be able to update the Kotlin version for Godot 4.3.

**Comment by kyadalu1** [comment]
@m4gr3d Its good to know that kotlin version will be updated for Godot 4.3 but when i try to change it manually like [this](https://github.com/godotengine/godot/issues/86152#issuecomment-1858891478) any idea why it still fails, what else do i need to update?

**Comment by m4gr3d** [comment]
> @m4gr3d Its good to know that kotlin version will be updated for Godot 4.3 but when i try to change it manually like [this](https://github.com/godotengine/godot/issues/86152#issuecomment-1858891478) any idea why it still fails, what else do i need to update?

@kyadalu1 The values shown in the `config.gradle` file match the [values used by the Godot Editor](https://github.com/godotengine/godot/blob/fbaab3cf537a892295aabdfd02c8052e370e6669/platform/android/java/app/config.gradle#L9) when it's exporting the Godot app binary. As such, any changes you make locally won't take effect since the values used by the Godot Editor remain the same.

**Comment by kyadalu1** [comment]
@m4gr3d Can you tell how to update the value in Godot Editor?

<img width="895" alt="Screenshot 2024-01-04 at 8 36 58 AM" src="https://github.com/m4gr3d/Godot-Android-Plugin-Template/assets/142881488/9061f374-5ae4-4c12-a221-2836178965bb">

I don't see updating the kotlin version option in above screenshot. 


Do i have to download godot source code, update kotlin version and somehow recompile the engine for it to take effect?

**Comment by m4gr3d** [comment]
The values cannot be updated from the Godot Editor.

> Do i have to download godot source code, update kotlin version and somehow recompile the engine for it to take effect?

Yes, you would have to rebuild the engine from source for the changes to take effect.

**Comment by myselfuser1** [comment]
@m4gr3d  Can we get kotlin 1.9.20 in Godot 4.3?

**Comment by m4gr3d** [comment]
> @m4gr3d Can we get kotlin 1.9.20 in Godot 4.3?

Done in https://github.com/godotengine/godot/pull/87346

**Comment by myselfuser1** [comment]
@m4gr3d Thank you so much
